name = "stranded"
compatibility_date = "2026-06-09"

[assets]
directory = "dist"

# Custom domain + silence the workers.dev warning
workers_dev = false

routes = [
  { pattern = "stranded.giveabit.io/*", custom_domain = true }
]
