/**
 * Auto-fill case study template from a site record.
 */
import { escapeHtml } from './html-escape'
import { fleetBlockMarkdown, type FleetExportBlock } from './fleet-template'

export type CaseStudySite = {
  id: string
  name?: string
  province?: string
  city?: string
  sourceType?: string
  score?: number
  emissionKgDay?: number
  gensetKw?: number
  confidence?: string
  company?: string
  potentialDailyCad?: number
  /** Optional fleet block carried into the document (additive, ignored when absent). */
  fleet?: FleetExportBlock
}

export function buildCaseStudyMarkdown(site: CaseStudySite, liveBtc = 85_000): string {
  const name = site.name || site.id
  const annualCad = site.potentialDailyCad != null ? Math.round(site.potentialDailyCad * 365) : null
  const lines = [
    `# Case study — ${name}`,
    '',
    `**Province:** ${site.province || '—'}  `,
    `**Source:** ${site.sourceType || '—'}  `,
    `**Stranded Score™:** ${site.score ?? '—'}  `,
    `**Confidence:** ${site.confidence || '—'}  `,
    `**Operator / company:** ${site.company || '—'}  `,
    '',
    '## Opportunity',
    `${name}${site.city ? ` near ${site.city}` : ''} vents or flares methane that can power on-site generation and Bitcoin mining with **zero net draw on the electrical grid**.`,
    '',
    '> ⚠️ Model scenarios: revenue uses a hashprice of 0.0000009 BTC/TH/day, ABOVE the network-derived estimate (~0.00000041 BTC/TH/day). These are optimistic-scenario figures, not a neutral forecast. Burning methane still emits CO₂ — the honest claim is ~28–80× lower warming impact per molecule (GWP₁₀₀ ≈ 28, GWP₂₀ ≈ 80), not "no emissions".',
    '',
    '## Key metrics',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Emission | ${site.emissionKgDay != null ? `${Math.round(site.emissionKgDay).toLocaleString()} kg CH₄/day` : '—'} |`,
    `| Modeled genset | ${site.gensetKw != null ? `${site.gensetKw} kW` : '—'} |`,
    `| Daily profit (model @ $${liveBtc.toLocaleString()} BTC) | ${site.potentialDailyCad != null ? `C$${Math.round(site.potentialDailyCad).toLocaleString()}` : '—'} |`,
    `| Annualized (simple) | ${annualCad != null ? `C$${annualCad.toLocaleString()}` : '—'} |`,
    '',
  ]
  if (site.fleet) {
    lines.push('## Fleet template')
    lines.push(fleetBlockMarkdown(site.fleet))
    lines.push('')
  }
  lines.push(
    '## Why it works',
    '1. Fuel is stranded — opportunity cost of methane destruction + energy is high.',
    '2. Mobile or modular gensets match emission scale.',
    '3. ASICs convert kWh into a globally liquid, verifiable commodity (BTC).',
    '4. Climate co-benefit: CH₄ abatement with measurable CO₂e equivalent.',
    '',
    '## Next diligence steps',
    '- Confirm flow rates and H₂S with site visit / SCADA',
    '- Land access + flaring permits',
    '- Interconnect not required (islanded microgrid)',
    '- Bank pack export from stranded.giveabit.io',
    '',
    `Deep link: https://stranded.giveabit.io/map?site=${encodeURIComponent(site.id)}`,
    '',
    '— Generated by Stranded Value · illustrative model · Safe Harbour',
  )
  return lines.join('\n')
}

export function buildCaseStudyHtml(site: CaseStudySite, liveBtc = 85_000): string {
  const md = buildCaseStudyMarkdown(site, liveBtc)
  const body = escapeHtml(md).replace(/\n/g, '<br/>')
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Case study — ${escapeHtml(site.name || site.id)}</title>
  <style>body{font-family:system-ui,sans-serif;max-width:720px;margin:32px;line-height:1.5;color:#0f172a}</style>
  </head><body><pre style="white-space:pre-wrap;font-family:inherit">${body}</pre></body></html>`
}
